### ISSUE TITLE
Bitcoin-S Wallet API Design Discussion

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#1284]

**Comment by nkohen** [comment]
Current interface is:

- `getbalance`
- `getnewaddress`
- `sendtoaddress`
- `rescan`

**Comment by nkohen** [comment]
Low hanging fruit (because they are already implemented in `WalletApi` but not `WalletRoutes`):

- separate calls for confirmed and unconfirmed balance
- `getUTXOs`
- `getAddresses`
- `getAccounts`
- `isEmpty`
- `getAddressInfo`
- `getNewAccount`

**Comment by Christewart** [comment]
So I think we need to get rid of `LockedWallet` and `UnlockedWallet`. If anything, we should rename the APIs to be something that requires a `KeyManager` to use, and something that does not require a key manager to use. 

For instance, listing all addresses in our current wallet should not require a `KeyManager`. However, sending a transaction should require a `KeyManager`. 

An interesting case is generating fresh addresses, if we are using BIP32 it appears that we would not need a key manager to generate a new address, however if we _arent_ using BIP32, I think we would need a `KeyManager`

**Comment by nkohen** [comment]
I think another related possibility is to have an ADT which has `KeyManager` as a subtype and `PublicKeyManager` as another for things like generating addresses (or perhaps `PublicKeyManager` should be a supertype of `KeyManager`). This way the wallet can just have a key or pubkey manager and act accordingly

**Comment by benthecarman** [comment]
Would be nice to have APIs for users to be able to send by doing their own coin control. Also to go with this would be good to have a send max/whole utxo(s).

**Comment by Kenny-zhao** [comment]
区块链企业钱包开放平台优盾钱包API接口官方文档：[https://www.uduncloud.com/gateway-interface](https://www.uduncloud.com/gateway-interface) 以供参考

**Comment by Christewart** [comment]
So since we are getting close to releasing v0.4 I thought I would put some more thought into this: 

Currently our [`WalletApi`](https://github.com/bitcoin-s/bitcoin-s/blob/7abca65ac458c327726ef7077fbc55fe9a2f4777/wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala#L45) interface contains too much stuff in my opinion. I'm especially concerned with us having clashes with the `WalletApi` and key manager work that we would like to do in v0.5. Here are my current thoughts:

The only methods that should be available in `WalletApi` are methods that should work for _every_ imaginable key manager. I'm going to hypothesize about 3 different key manager types for the sake of this issue: 

1. A single private key (every address is a re-used address!)
2. A HD key chain
3. A bag of keys where every key is completely independent of one another

What kind of `WalletApi` can we offer that accommodates all 3 types of these key chains?  

At the end of the day, I would like to be more judicious with the the `v0.4` release of bitcoin-s. It's always easier to add new things to the interface but much more difficult to deprecate things.

Here are my proposals: 

1. Move `WalletApi` into the core project similar to `ChainApi`, `NodeApi` etc. 
2. Remove all `HDAccount` specific stuff from the `WalletApi` and create a subclass of `WalletApi` that is called `HDWallet`.
3. Move all "locking" and "unlocking" stuff out of the `WalletApi` as this seems like an implementation detail to me
4. Move all neutrino/rescan stuff out of the `WalletApi` 
5. Change [`keyManager`](https://github.com/bitcoin-s/bitcoin-s/blob/7abca65ac458c327726ef7077fbc55fe9a2f4777/wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala#L485) return type to be `KeyManager` rather than `BIP39KeyManager`. 


Again, I think we should start with a "thin" interface for now and implement essentially what is in the `WalletApi` in a subclass for now. We should try and implement the different versions of the `WalletApi` as subclasses that allow you to exploit the unique functionality for each one.  

I'm not sure what this means for compatabillity with existing wallets generated in bitcoin-s, but I think this is the right step forward for design.

**Comment by benthecarman** [comment]
We should also remove

```
  implicit val walletConfig: WalletAppConfig
  implicit val ec: ExecutionContext
```
from the WalletApi, both our `ChainApi` and `NodeApi`s don't have their respective app configs either

**Comment by benthecarman** [comment]
Moving the `WalletApi`s to `core` will be require some extra work, currently, `WalletApi` uses a lot of datatypes that are not accessible from `core`, some being from `wallet` some being from `appCommons`.
