### ISSUE TITLE
Remove circular dependency for Node callbacks

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#1487]
Stemming from this conversation https://github.com/bitcoin-s/bitcoin-s/pull/1481#discussion_r432623817

Currently, using wallet callbacks with a `Node` has a circular dependency. A wallet takes in a `NodeApi` but for a `Node` to have it's callbacks set it needs a `Wallet` to call the functions on.

**Comment by Christewart** [comment]
Is this related to #1542 ?

**Comment by benthecarman** [comment]
No :(

**Comment by benthecarman** [comment]
> Is this related to #1542 ?

No :(

**Comment by Christewart** [comment]
This seems to persist in some work that Roman is doing with chain watchers in Eclair, so this is a design issue.

**Comment by Christewart** [comment]
Some thoughts on API design: 

I think callbacks should be added to an `AppConfig` rather than directly on a `Node`, `ChainHandler` etc. This is because the `AppConfig` is passed through the application via implicits, therefore we can propagate modifications to the callbacks easily. This is similar to how an `ActorSystem` is propogated throughout your akka application. With an actorsystem, you can register a callback with `system.eventStream.subscribe()` 

One concern I have with this design:

Are we putting too much stuff into `AppConfig`? It seems like we already have a lot of stuff in there, and maybe we need to think about structuring it differently? Overall I think we _should_ put callbacks in there, but it's worth thinking about the design a bit to make sure we don't just end up stuffing everything into an `AppConfig` as a fix to all of our problems.

**Comment by nkohen** [comment]
Generally speaking I am cool with the idea of putting callbacks on the `AppConfig` so that they propagate implicitly, I would just ask that it be on like a `case class` that the `AppConfig` `has-a` rather than directly on the `AppConfig` as like a `Map` or something like that.

**Comment by benthecarman** [comment]
Concept ACK from me, main problem I see is that the wallet project doesn't depend on the node project currently, and same goes for the inverse.

**Comment by Christewart** [comment]
> Concept ACK from me, main problem I see is that the wallet project doesn't depend on the node project currently, and same goes for the inverse.

Hmm, what do you mean by this? We shouldn't need to register a callback for the node project inside of the wallet module should we? This should be the responsibility of middle ware (such as `appServer`) no?

**Comment by benthecarman** [comment]
>  We shouldn't need to register a callback for the node project inside of the wallet module

The `WalletAppConfig` is in the wallet module and the `NodeAppConfig` is in the node module. So one would have to depend on the other.

**Comment by Christewart** [comment]
> > We shouldn't need to register a callback for the node project inside of the wallet module
> 
> The `WalletAppConfig` is in the wallet module and the `NodeAppConfig` is in the node module. So one would have to depend on the other.

Yes. I guess i'm confused what your point is. The wallet module shouldn't know about the node module other than `NodeApi` and vice versa

**Comment by benthecarman** [comment]
> Yes. I guess i'm confused what your point is. The wallet module shouldn't know about the node module other than NodeApi and vice versa

They will need to know about each other, if we want one to add the callbacks

**Comment by Christewart** [comment]
> > Yes. I guess i'm confused what your point is. The wallet module shouldn't know about the node module other than NodeApi and vice versa
> 
> They will need to know about each other, if we want one to add the callbacks

Yeah, I don't think callbacks should be added by the wallet/node modules. I'm talking about third party middlware doing it, for instance `appServer` or code that @rorp is working on for eclair. I don't think the two modules should be registering callbacks on each other _within_ their respective modules.

**Comment by benthecarman** [comment]
I am confused then how the `AppConfig` comes into play

**Comment by Christewart** [comment]
Because `AppConfig` is how you configure our modules. You should always have a reference to the `AppConfig` (similar to how we always have a reference to a `ActorSystem` or a `ExecutionContext`) when dealing with a bitcoin-s module. If you want to register a callback you can just do `appConfig.register(callback)`

**Comment by benthecarman** [comment]
Ohhh, okay that makes more sense. Was thinking we were making a function on the `WalletAppConfig` that would return a `NodeCallbacks`, but you want to make the `NodeCallbacks` in `Main` and then add them through the `NodeAppConfig`.
