### ISSUE TITLE
bitcoin-s-cli needs tagging functionality

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1784]
I think we should be able to

1. Tag a address 
2. Tag a utxo
3. Remove tag from an address
4. Remove tag from utxo
5. Create a tag
6. Remove a tag (should default functionality be we remove the tag from all utxos associated with this tag?)

Am I missing anything ?

**Comment by benthecarman** [comment]
We actually only support tagging addresses not individual utxos, utxos get implicitly tagged by the address they are associated with. This is because all utxos under the same address should be considered associated because if a party knows that address X belongs to you, then they will know every utxo associated with that address also belongs to you.
