### ISSUE TITLE
Error in cloning repository with all submodules using command given in documentation

### ISSUE THREAD

**Issue by solo1g** [bitcoin-s/bitcoin-s#3389]
There are 2 minor issues that occur in the step 2 of [getting setup](https://bitcoin-s.org/docs/getting-setup) part of documentation as per the clone commands given.
* On a machine with ssh not configured, `git clone --depth 500 --recursive https://github.com/bitcoin-s/bitcoin-s.git` this is suggested to be used but it fails to clone secp256k1-zkp repo.
![image](https://user-images.githubusercontent.com/56965282/125177401-1035ce00-e1f9-11eb-86cc-d3322379fc8a.png)
* On a machine with ssh configured, it would still fail with the same output if no key corresponding to host `github.com` exists. I had 2 keys with one which uses git@insti and other git@other.

This error occurs as the ssh url with `github.com` as host is hardcoded in the [.gitmodules](https://github.com/bitcoin-s/bitcoin-s/blob/master/.gitmodules) file.

The solution is to just use https url in `.gitmodules` file instead of ssh.
```ruby
[submodule "secp256k1-zkp"]
	path = secp256k1-zkp
	url = https://github.com/bitcoin-s/secp256k1-zkp.git
```

**Comment by Christewart** [comment]
@shreyanshyad In the future when submitting patches make sure to use the syntax so that github will actually close the issue :-) I.e. if you would have used the keyword "fixes" rather than "for" this would automatically close 

![Screenshot from 2021-07-12 08-26-58](https://user-images.githubusercontent.com/3514957/125295557-f379c300-e2ea-11eb-8800-6674f6c7b2d4.png)

**Comment by solo1g** [comment]
Oh, didn't know about that. Thanks for the info!
