### ISSUE TITLE
Rethink `DEFAULT_BITCOIND_LOCATION` exception safety

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3466]
I've been working through a problem with @shruthii625 about implementing cookie based authentication in bitcoin-s (#2891). 

One issue she has had is downloading bitcoind and configuring bitcoin-s to where the binary lives with the configuration key 

`bitcoin-s.bitcoind-rpc.binary`

This leads us to a default helper `val` we provide called `DEFAULT_BITCOIND_LOCATION` 

This is causing us problems on multiple fronts: 

1. [It assumes bitcoind is on your path](https://github.com/bitcoin-s/bitcoin-s/blob/1e87cb0fdecea0e67eb2679ee6c7b47ad644d72c/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala#L107)
2. [It throws exceptions eagerly if the place is not defined!](https://github.com/bitcoin-s/bitcoin-s/blob/1e87cb0fdecea0e67eb2679ee6c7b47ad644d72c/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala#L120)

## What we need to do 

1. We need to modify the return type from `File` to `Option[File]` so we don't have exceptions thrown eagerly
2. Everywhere we there are compiler errors, we need to handle the `None` case by referring to the binary configured in `bitcoin-s.bitcoind-rpc.binary`

**Comment by benthecarman** [comment]
ACK, currently we have an `isRemote` option which will skip the file checks but is annoying because it requires us still to put a `File` for the `binary` and the `datadir`.

It might be better to split up `BitcoindInstance` and/or `BitcoindRpcClient` into 2 separate types, one that is for a locally running bitcoind and will start the binary, and one that is for a "remote" bitcoind where it won't start the binary and do the file checks.

**Comment by Christewart** [comment]
Done in #3600
