### ISSUE TITLE
CreateDigitDecompEvent through oracleServer not creating event

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3611]
I have not been able to get a DigitDecompEvent to create via OracleRoutes yet. I see [ServerJsonModels.scala:116](https://github.com/bitcoin-s/bitcoin-s/blob/2b8ac08cdcb161fe5d7b6c9916f884b291bab9f9/app/oracle-server/src/main/scala/org/bitcoins/oracle/server/ServerJsonModels.scala#L116) CreateDigitDecompEvent.fromJsArr matching
```scala
case labelJs :: maturationTimeJs :: baseJs :: isSignedJs :: numDigitsJs :: unitJs :: precisionJs
```
and I've sent data like 
```json
["digitdecompEvent", "2030-01-01T00:00:00.000Z", 2, true, 3, "Unit", 0]
```
as params, full payload like 
```json
{"method":"createdigitdecompevent","params":["digitdecompEvent","2030-01-01T00:00:00.000Z",2,false,3,"Unit",0]}
```
**To Reproduce**
Best route is probably curl similar to https://bitcoin-s.org/docs/next/oracle/oracle-server examples or new oracle-server-ui.

**Expected behavior**
New DigitDecompEvent created

**Logs**
There are no sever-side error logs around this

**Platform (please complete the following information):**
Mac, newest

**Comment by Christewart** [comment]
So with the `createdigitdecompevent` rpc you need to use seconds since epoch rather than datetime. 

https://bitcoin-s.org/docs/oracle/oracle-price-example#createdigitdecompevent-rpc

```json
{"method":"createdigitdecompevent","params":["digitdecompEvent","2030-01-01T00:00:00.000Z",2,false,3,"Unit",0]}
```
I think this needs to be 

```json
{"method":"createdigitdecompevent","params":["digitdecompEvent",1893456000,2, false, 3,"Unit",0]}
```

I've added a test here for this case: https://github.com/Christewart/bitcoin-s-core/commit/b502041eaee516e9d55a1e817ba71d884a074b41#diff-c0f16feba9a069388ed05bb040aaa120e23e9b0c37d0d4e5d537fb590259e259R272

**Comment by user411** [comment]
Your insight worked. Totally missed the different typing there.
