### ISSUE TITLE
Consider renaming `WitnessScriptPubKeyV1` -> `TaprootScriptPubKey`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3988]
> Maybe should rename witness spk v1 to Taproot spk since it doesn't cover all witness v1 spks

I think it's a good idea. Any objections @nkohen ?

_Originally posted by @Christewart in https://github.com/bitcoin-s/bitcoin-s/issues/3987#issuecomment-1014858660_

**Comment by benthecarman** [comment]
Currently taproot a taproot spk is defined by a witness v1 spk with a 32 byte schnorr pub key. Since something like a 33 byte pubkey isn't defined yet but is still a witness v1 spk I think it makes sense to distinguish the two

https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#script-validation-rules
